version: 1.2
workflows:
- name: GraphEvaluation
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GraphEvaluation.wdl
  testParameterFiles:
- name: hapestry_validate
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/hapestry_validate.wdl
  testParameterFiles: